name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18, 20, 21]
        nuxt: ['3', '4']

    name: Test (Node ${{ matrix.node }} - Nuxt ${{ matrix.nuxt }})

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Install Nuxt ${{ matrix.nuxt }}
        run: |
          if [ "${{ matrix.nuxt }}" = "3" ]; then
            npm install nuxt@^3.0.0 --save-dev
          else
            npm install nuxt@^4.0.0 --save-dev
          fi

      - name: Run linter
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Build module
        run: npm run prepack

      - name: Type check
        run: npm run test:types
        continue-on-error: true

  coverage:
    runs-on: ubuntu-latest
    name: Coverage Report

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate coverage
        run: npm run test:coverage
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
